### ISSUE TITLE
error on $make for amd raid drive on Fedora 30

### ISSUE THREAD

**Issue by wesleysidney** [martinkarlweber/rcraid-patches#13]
i have no experience in programing, and i think it is needed to fix this thing, i am trying to install raid drivers on fedora 30 for 3 days and i did compiled a kernel following the instructions in a blog called frdmtoplay... and after all i have problems in the make thing, when i go inside ~/driver_sdk/src/ and execute the $sudo make, it give the error:

 

------------------------------------------------------------
- building for kernel 5.2.5-201.raid.fc30.x86_64
------------------------------------------------------------
make -C /lib/modules/5.2.5-201.raid.fc30.x86_64/build SUBDIRS=/home/wesley/driver_sdk/src modules
make[1]: Entering directory '/usr/src/kernels/5.2.5-201.raid.fc30.x86_64'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
  CC [M]  /home/wesley/driver_sdk/src/rc_init.o
In file included from /home/wesley/driver_sdk/src/rc.h:98,
                 from /home/wesley/driver_sdk/src/rc_init.c:39:
/home/wesley/driver_sdk/src/rc_adapter.h:43: warning: "SECTOR_SIZE" re-definido
   43 | #define SECTOR_SIZE         512
      |
In file included from /home/wesley/driver_sdk/src/rc.h:40,
                 from /home/wesley/driver_sdk/src/rc_init.c:39:
./include/linux/blkdev.h:895: note: essa é a localização da definição anterior
  895 | #define SECTOR_SIZE (1 << SECTOR_SHIFT)
      |
/home/wesley/driver_sdk/src/rc_init.c:332:29: error: initialization of ‘int (*)(struct scsi_device *, unsigned int,  void *)’ from incompatible pointer type ‘int (*)(struct scsi_device *, int,  void *)’ [-Werror=incompatible-pointer-types]
  332 |  .ioctl =                   rc_ioctl,
      |                             ^~~~~~~~
/home/wesley/driver_sdk/src/rc_init.c:332:29: note: (near initialization for ‘driver_template.ioctl’)
/home/wesley/driver_sdk/src/rc_init.c:346:3: error: ‘Scsi_Host_Template’ {aka ‘struct scsi_host_template’} has no member named ‘use_clustering’
  346 |  .use_clustering =          ENABLE_CLUSTERING,
      |   ^~~~~~~~~~~~~~
/home/wesley/driver_sdk/src/rc_init.c:346:29: error: ‘ENABLE_CLUSTERING’ undeclared here (not in a function)
  346 |  .use_clustering =          ENABLE_CLUSTERING,
      |                             ^~~~~~~~~~~~~~~~~
/home/wesley/driver_sdk/src/rc_init.c: In function ‘rc_timeout_done’:
/home/wesley/driver_sdk/src/rc_init.c:2392:2: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
 2392 |  init_timer(&state->rc_timeout);
      |  ^~~~~~~~~~
      |  init_timers
/home/wesley/driver_sdk/src/rc_init.c: In function ‘rc_timeout’:
/home/wesley/driver_sdk/src/rc_init.c:2408:19: error: ‘struct timer_list’ has no member named ‘data’
 2408 |  state->rc_timeout.data = (unsigned long)state;
      |                   ^
/home/wesley/driver_sdk/src/rc_init.c:2409:29: error: assignment to ‘void (*)(struct timer_list *)’ from incompatible pointer type ‘void (*)(long unsigned int)’ [-Werror=incompatible-pointer-types]
 2409 |  state->rc_timeout.function = rc_timeout_done;
      |                             ^
/home/wesley/driver_sdk/src/rc_init.c: In function ‘rcraid_resume_one’:
/home/wesley/driver_sdk/src/rc_init.c:1096:9: warning: ignoring return value of ‘pci_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
 1096 |         pci_enable_device(adapter->pdev);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/driver_sdk/src/rc_init.c:1121:5: warning: ignoring return value of ‘pcim_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
 1121 |     pcim_enable_device(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/wesley/driver_sdk/src/rc_init.o] Error 1
make[1]: *** [Makefile:1600: _module_/home/wesley/driver_sdk/src] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.2.5-201.raid.fc30.x86_64'
make: *** [Makefile:60: all] Error 2

 

 

may anyone help me here?

**Comment by wesleysidney** [comment]
i made the same changes as quizzicus in rc_init.c, line 168 i changed to 

int rc_ioctl(struct scsi_device * scsi_dev_ptr, unsigned int cmd, void *arg);

line 1973 i also changed:

unsigned int cmd,

now i got this result when i try to make:

------------------------------------------------------------
- building for kernel 5.2.5-201.raid.fc30.x86_64
------------------------------------------------------------
make -C /lib/modules/5.2.5-201.raid.fc30.x86_64/build SUBDIRS=/home/wesley/Downloads/driver_sdk/src modules
make[1]: Entering directory '/usr/src/kernels/5.2.5-201.raid.fc30.x86_64'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
ln -sf `basename /home/wesley/Downloads/driver_sdk/src/rcblob.x86_64.o .o` /home/wesley/Downloads/driver_sdk/src/rcblob.x86_64.o
  CC [M]  /home/wesley/Downloads/driver_sdk/src/rc_init.o
/home/wesley/Downloads/driver_sdk/src/rc_init.c: In function ‘rcraid_resume_one’:
/home/wesley/Downloads/driver_sdk/src/rc_init.c:1101:9: warning: ignoring return value of ‘pci_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
 1101 |         pci_enable_device(adapter->pdev);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wesley/Downloads/driver_sdk/src/rc_init.c:1126:5: warning: ignoring return value of ‘pcim_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
 1126 |     pcim_enable_device(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /home/wesley/Downloads/driver_sdk/src/rc_msg.o
  CC [M]  /home/wesley/Downloads/driver_sdk/src/rc_mem_ops.o
  CC [M]  /home/wesley/Downloads/driver_sdk/src/rc_event.o
  CC [M]  /home/wesley/Downloads/driver_sdk/src/rc_config.o
  CC [M]  /home/wesley/Downloads/driver_sdk/src/vers.o
  LD [M]  /home/wesley/Downloads/driver_sdk/src/rcraid.o
  Building modules, stage 2.
  MODPOST 1 modules
FATAL: modpost: GPL-incompatible module rcraid.ko uses GPL-only symbol '__init_work'
make[2]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
make[1]: *** [Makefile:1604: modules] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.2.5-201.raid.fc30.x86_64'
make: *** [Makefile:60: all] Error 2
ERROR: Failed to build the RAIDCORE Drivers.
Please make sure kernel source rpm is installed for 5.2.5-201.raid.fc30.x86_64.

**Comment by quizzicus** [comment]
This is how I got around it: https://devtalk.nvidia.com/default/topic/989778/linux/nvidia-drivers-378-09-fails-to-build-fatal-modpost-gpl-incompatible-module-nvidia-drm-ko-uses-gpl-only-symbol-mutex_destroy-/post/5172009/#5172009

**Comment by wesleysidney** [comment]
i have no ideia how to aply that patch to kernel... lol

**Comment by wesleysidney** [comment]
anyone know how do i aply this patch to kernel source?  

>     diff -durN linux-4.2.0/include/linux/export.h linux-4.2.0-patched/include/linux/export.h
    --- linux-4.2.0/include/linux/export.h	2015-08-30 20:34:09.000000000 +0200
    +++ linux-4.2.0-patched/include/linux/export.h	2015-08-31 16:35:20.620645230 +0200
    @@ -69,14 +69,14 @@
     	__EXPORT_SYMBOL(sym, "")
     
     #define EXPORT_SYMBOL_GPL(sym)					\
    -	__EXPORT_SYMBOL(sym, "_gpl")
    +	__EXPORT_SYMBOL(sym, "")
     
     #define EXPORT_SYMBOL_GPL_FUTURE(sym)				\
    -	__EXPORT_SYMBOL(sym, "_gpl_future")
    +	__EXPORT_SYMBOL(sym, "")
     
     #ifdef CONFIG_UNUSED_SYMBOLS
     #define EXPORT_UNUSED_SYMBOL(sym) __EXPORT_SYMBOL(sym, "_unused")
    -#define EXPORT_UNUSED_SYMBOL_GPL(sym) __EXPORT_SYMBOL(sym, "_unused_gpl")
    +#define EXPORT_UNUSED_SYMBOL_GPL(sym) __EXPORT_SYMBOL(sym, "_unused")
     #else
     #define EXPORT_UNUSED_SYMBOL(sym)
     #define EXPORT_UNUSED_SYMBOL_GPL(sym)

>

**Comment by wesleysidney** [comment]
diff -durN linux-4.2.0/include/linux/export.h linux-4.2.0-patched/include/linux/export.h

    --- linux-4.2.0/include/linux/export.h	2015-08-30 20:34:09.000000000 +0200
    +++ linux-4.2.0-patched/include/linux/export.h	2015-08-31 16:35:20.620645230 +0200
    @@ -69,14 +69,14 @@
     	__EXPORT_SYMBOL(sym, "")
     
     #define EXPORT_SYMBOL_GPL(sym)					\
    -	__EXPORT_SYMBOL(sym, "_gpl")
    +	__EXPORT_SYMBOL(sym, "")
     
     #define EXPORT_SYMBOL_GPL_FUTURE(sym)				\
    -	__EXPORT_SYMBOL(sym, "_gpl_future")
    +	__EXPORT_SYMBOL(sym, "")
     
     #ifdef CONFIG_UNUSED_SYMBOLS
     #define EXPORT_UNUSED_SYMBOL(sym) __EXPORT_SYMBOL(sym, "_unused")
    -#define EXPORT_UNUSED_SYMBOL_GPL(sym) __EXPORT_SYMBOL(sym, "_unused_gpl")
    +#define EXPORT_UNUSED_SYMBOL_GPL(sym) __EXPORT_SYMBOL(sym, "_unused")
     #else
     #define EXPORT_UNUSED_SYMBOL(sym)
     #define EXPORT_UNUSED_SYMBOL_GPL(sym)

i have no ideia where to start, i jund a folder on my lunux kernel source 

linux-5.2.6-201.raid.fc30.x86_64/include/linux/export.h

that have the export.h file, but i dont know what to do... anyone help?

**Comment by wesleysidney** [comment]
ok all the problem was becouse i was using an kernel with debug on, after 5 hours compiling a nodebug kernel i am now with the raid working, everithing compiled and worked like a clock, ty for the patch guys.
