### ISSUE TITLE
Makefile detects wrong machine type

### ISSUE THREAD

**Issue by llitz** [martinkarlweber/rcraid-patches#4]
When building on my machine "uname -i" returns AuthenticAMD, failing to build the rcblob.

Changing the PLATFORM detection to "uname -m" fix the issue and should be compatible on other systems as this is the one that return sane values.

This link can work as reference: [What uname returns on different architectures](https://www.linuxquestions.org/questions/mandriva-30/what-does-uname-return-on-different-architectures-922669)

**Comment by martinkarlweber** [comment]
Thanks for notifying me. You are right. I will update the patch.

**Comment by martinkarlweber** [comment]
Patch updated.
