### ISSUE TITLE
Kernel 4.20 (missing symbols)

### ISSUE THREAD

**Issue by DestroyFX** [martinkarlweber/rcraid-patches#7]
Hi there, I tried to build that and I noticed that the install script was building it for my whole kernel collection but there is an issue!

From kernel 4.20, I get that errors during modpost and the module fail to load obviously.
WARNING: "RC_EnableAN" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_ODD_GpeNumber" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_BUILD_NUMBER" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_ODDZDevAddr" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_EnableHIPM" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_OurInterfaceStruct" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_EnableZPODD" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_EnableNCQ" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_EnableDIPM" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!
WARNING: "RC_ODD_Device" [/usr/src/amdraid/driver_sdk/src/rcraid.ko] undefined!

**Comment by mltrx** [comment]
Same here on Arch Linux. @DestroyFX Which linux distro do you use?

**Comment by DestroyFX** [comment]
@michaltrzcinski Gentoo

**Comment by Herrie82** [comment]
Same here on (K)Ubuntu 18.04 with 4.20.7 kernel:

herriemerim@herriemerim-desktop:~$ dmesg | grep rcraid
[    1.208190] rcraid: loading out-of-tree module taints kernel.
[    1.208203] rcraid: module license 'Proprietary' taints kernel.
[    1.208577] rcraid: module verification failed: signature and/or required key missing - tainting kernel
[    1.208630] rcraid: Unknown symbol RC_ODD_Device (err -2)
[    1.208637] rcraid: Unknown symbol RC_EnableDIPM (err -2)
[    1.208669] rcraid: Unknown symbol RC_EnableNCQ (err -2)
[    1.208682] rcraid: Unknown symbol RC_EnableZPODD (err -2)
[    1.208688] rcraid: Unknown symbol RC_OurInterfaceStruct (err -2)
[    1.208707] rcraid: Unknown symbol RC_EnableHIPM (err -2)
[    1.208713] rcraid: Unknown symbol RC_ODDZDevAddr (err -2)
[    1.208727] rcraid: Unknown symbol RC_BUILD_NUMBER (err -2)
[    1.208737] rcraid: Unknown symbol RC_ODD_GpeNumber (err -2)
[    1.208751] rcraid: Unknown symbol RC_EnableAN (err -2)
[    2.500572] rcraid: Unknown symbol RC_ODD_Device (err -2)
[    2.500581] rcraid: Unknown symbol RC_EnableDIPM (err -2)
[    2.500607] rcraid: Unknown symbol RC_EnableNCQ (err -2)
[    2.500621] rcraid: Unknown symbol RC_EnableZPODD (err -2)
[    2.500628] rcraid: Unknown symbol RC_OurInterfaceStruct (err -2)
[    2.500645] rcraid: Unknown symbol RC_EnableHIPM (err -2)
[    2.500651] rcraid: Unknown symbol RC_ODDZDevAddr (err -2)
[    2.500666] rcraid: Unknown symbol RC_BUILD_NUMBER (err -2)
[    2.500678] rcraid: Unknown symbol RC_ODD_GpeNumber (err -2)
[    2.500691] rcraid: Unknown symbol RC_EnableAN (err -2)
[    3.200208] rcraid: Unknown symbol RC_ODD_Device (err -2)
[    3.200220] rcraid: Unknown symbol RC_EnableDIPM (err -2)
[    3.200251] rcraid: Unknown symbol RC_EnableNCQ (err -2)
[    3.200268] rcraid: Unknown symbol RC_EnableZPODD (err -2)
[    3.200277] rcraid: Unknown symbol RC_OurInterfaceStruct (err -2)
[    3.200299] rcraid: Unknown symbol RC_EnableHIPM (err -2)
[    3.200309] rcraid: Unknown symbol RC_ODDZDevAddr (err -2)
[    3.200325] rcraid: Unknown symbol RC_BUILD_NUMBER (err -2)
[    3.200339] rcraid: Unknown symbol RC_ODD_GpeNumber (err -2)
[    3.200355] rcraid: Unknown symbol RC_EnableAN (err -2)

**Comment by Herrie82** [comment]
When moving back to 4.19.20 things work fine again:

[    2.008858] rcraid: loading out-of-tree module taints kernel.
[    2.008865] rcraid: module license 'Proprietary' taints kernel.
[    2.010010] rcraid: module verification failed: signature and/or required key missing - tainting kernel
[    2.013276] <5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built feb 08 2019
[    2.013278] <5>rcraid built on herriemerim-desktop by root on vr  8 feb 2019 20:46:55 CET
[    2.013279] <5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
[    2.014116] <5>rcraid_probe_one: vendor = 0x1022 device 0x43bd
[    2.014125] <5>rcraid_probe_one: Total adapters matched 1
[    2.015846] <5>rcraid: rc_init_adapter 64 bit DMA enabled
[    2.015946] <3>rcraid:0 request_threaded_irq irq 149
[    2.015950] <5>rcraid: card 0: AMD, Inc. AHCI
[    4.121995] rcraid: (1549655378.531816)
[    4.432064] <6>rcraid: rc_event: config change detected on bus 0

**Comment by martinkarlweber** [comment]
Found the cause of the problem, need a few days to work on the solution and to prepare a fix.

**Comment by Herrie82** [comment]
Great! I'm back on 4.19 now, but good to see you found the cause. Looking forward to the fix. Curious to understand what caused it and what the fix will be.

**Comment by martinkarlweber** [comment]
The problem is that the kernel build system changed such that rcblob.* is not picked up in the linking process. I was able to run it manually once for 4.20.7 and the module built nicely, but have to adopt the Makefile / install script.

**Comment by Herrie82** [comment]
@martinkarlweber Might be good to do it directly on the dkms repo from @thopiekar ? The source files are there too and we'll have DKMS as added benefit :) https://github.com/thopiekar/rcraid-dkms

**Comment by thopiekar** [comment]
@Herrie82 Thank you for the mention.
I would be glad to get the patch applied on my repo. Once applied, updated DKMS packages will be rolled out automatically.

**Comment by martinkarlweber** [comment]
The problem is that the kernel build system changed such that rcblob.* is not picked up in the linking process. I was able to run it manually once for 4.20.7 and the module built nicely, but have to adopt the Makefile / install script.

**Comment by martinkarlweber** [comment]
Patch is out, look at newest version of this repository. For easier integration in dkms, have a look at file [rcraid-dkms.patch.zip](https://github.com/martinkarlweber/rcraid-patches/files/2873004/rcraid-dkms.patch.zip) that contains only the patch to the Makefile. If I had more time I would add this myself to the [dkms-repo] from @thopiekar. Good luck and thanks for the bug report. Let me know if you have problems.

**Comment by Herrie82** [comment]
Great stuff! Will give it a go :)

**Comment by thopiekar** [comment]
Is the change also backwards compatible?
Personally I see no reason why it shouldn't, but I can only guess.

**Comment by martinkarlweber** [comment]
Yes, it is backwards compatible. I could run the patch as well on kernel 4.18. If you have problems, let me know.
